dataset_path: ./dataset/ucf_action_grouped_augmented_ttv_mp4/
#dataset_path: /mnt/disco_esterno/ucf_sports_actions/ucf action/
path_dataset_train_csv: df_train.csv
path_dataset_val_csv: df_val.csv
path_dataset_test_csv: df_test.csv
saving_dir_experiments: ./exps_ucf_action/ucf_action_grouped_augmented_v2/
saving_dir_model: models_augmented_v2
num_classes: 10
num_epoch: 10
batch_size: 4
num_frames: 64
sampling_rate: 8
frames_per_second: 10
path_torchvideo_model: facebookresearch/pytorchvideo
name_torchvideo_model: slow_r50
learning_rate: 0.001
scheduler_step_size: 3
scheduler_gamma: 0.1
crop_video: 1
freeze_layers: 1
epoch_start_unfreeze: 5
n_nodes: 128
dropout: 0.3
block_start_unfreeze: 4
do_train: 1
do_test: 1